version: '3'
services:
  nexus:
    image: sonatype/nexus3:3.0.0
    container_name: nexus
    ports:
     - "8081:8081"
     - "8082:8082"
     - "8083:8083"
    volumes:
    - /opt/nexus:/nexus-data